[package]
name = "agent-agency-production"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "agent_agency_production"
path = "mod.rs"

[dependencies]
# Workspace dependencies
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true

# Local crates
agent-agency-contracts = { path = "../agent-agency-contracts" }

# Additional dependencies
anyhow = "1.0"