[package]
name = "self-prompting-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-agency-contracts = { path = "../agent-agency-contracts" }
# orchestration = { path = "../orchestration" }  # TEMP: disabled - compilation issues
# reflexive-learning = { path = "../reflexive-learning" }  # TEMP: disabled - torch issues
# agent-agency-workers = { path = "../workers" }  # TEMP: disabled - compilation issues
# agent-agency-apple-silicon = { path = "../apple-silicon" }  # TEMP: disabled - compilation issues
file_ops = { path = "../file_ops" }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true, features = ["serde"] }
async-trait = { workspace = true }
reqwest = { version = "0.11", features = ["json"] }
diffy = "0.3"
git2 = "0.19"
tempfile = "3.8"
rand = "0.8"
regex = "1.10"
tokenizers = "0.15"  # HuggingFace tokenizers for proper text tokenization

# Action request parsing
pest = "2.7"  # PEG parser for formal grammars
pest_derive = "2.7"  # Derive macros for pest
nom = "7.1"  # Parser combinators for robust parsing

# Additional dependencies for self-prompting-agent
thiserror = "1.0"
sha2 = "0.10"
hdrhistogram = "7.5"
metrics = "0.22"
cpu-time = "1.0"
memory-stats = "1.2"
serde_yaml = "0.9"
similar = "2.4"

[[example]]
name = "playground_test"
path = "examples/playground_test.rs"
