apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-agency-redis
  namespace: agent-agency
  labels:
    app: agent-agency-redis
    component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-agency-redis
  template:
    metadata:
      labels:
        app: agent-agency-redis
        component: cache
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: agent-agency-cache
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          command:
            - redis-server
            - --appendonly
            - --appendfsync
            - everysec
            - --maxmemory
            - 512mb
            - --maxmemory-policy
            - allkeys-lru
            - --tcp-keepalive
            - "300"
            - --timeout
            - "300"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: redis-data
              mountPath: /data
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          ports:
            - containerPort: 9121
              name: metrics
              protocol: TCP
          env:
            - name: REDIS_ADDR
              value: "redis://127.0.0.1:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agent-agency-secrets
                  key: redis-password
                  optional: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: agent-agency-redis-pvc
