// TTS-related TypeScript types

export interface TTSVoice {
  id: string;
  name: string;
  language: string;
  gender: 'male' | 'female' | 'neutral';
  quality?: string;
  description?: string;
}

export interface TTSRequest {
  text: string;
  voice?: string;
  speed?: number;
  stream?: boolean;
}

export interface TTSResponse {
  audioUrl?: string;
  audioBlob?: Blob;
  duration?: number;
  error?: string;
}

export interface TTSSettings {
  enabled: boolean;
  autoPlayAgentResponses: boolean;
  autoPlayNotifications: boolean;
  voice: string;
  speed: number;
  volume: number;
  notificationSound: boolean;
  attentionAlerts: boolean;
}

export interface AudioPlaybackState {
  isPlaying: boolean;
  isLoading: boolean;
  currentTime: number;
  duration: number;
  volume: number;
  error?: string;
}

export interface NotificationAlert {
  id: string;
  type: 'attention' | 'voicemail' | 'task_complete' | 'error';
  message: string;
  userName?: string;
  priority: 'low' | 'medium' | 'high';
  timestamp: string;
  played: boolean;
}

export interface TTSMessageMetadata {
  hasAudio: boolean;
  audioUrl?: string;
  audioDuration?: number;
  voiceUsed?: string;
  autoGenerated?: boolean;
}
