[package]
name = "agent-agency-caching"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
futures.workspace = true

# Caching dependencies
redis = { version = "0.25", features = ["tokio-comp", "connection-manager"] }
rand = "0.8"
sqlparser = "0.45"  # SQL parsing and AST analysis
once_cell = "1.5"  # Lazy static initialization
typetag = "0.2"  # Runtime type reflection for serialization
inventory = "0.3"  # Plugin system for cache types
erased-serde = "0.3"  # Type-erased serialization
flate2 = "1.0"  # Compression/decompression
