[package]
name = "recovery"
version = "0.1.0"
edition = "2021"
authors = ["@darianrosebrook"]
description = "Content-Addressable Storage for V3 Recovery System"

[dependencies]
# Core dependencies
blake3 = "1.5"
zstd = "0.13"
flate2 = "1.0"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"

# Content processing
similar = "2.0"       # Unified diffs
fastcdc = "3.0"       # CDC with gear hash

# File system operations
walkdir = "2.0"
glob = "0.3"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# CLI
clap = { version = "4.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Pattern matching
regex = "1.0"

# Hex encoding
hex = "0.4"

# Serialization
bincode = "1.3"

# YAML support
serde_yaml = "0.9"

# Logging
tracing-subscriber = "0.3"

# Local dependencies
# source-integrity = { path = "../source-integrity" }  # Temporarily disabled due to compilation issues

[dev-dependencies]
proptest = "1.0"
tempfile = "3.0"
tokio-test = "0.4"

[[bin]]
name = "recov"
path = "src/bin/recov.rs"
