[package]
name = "reflexive-learning"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true

# Learning and optimization
ndarray.workspace = true
petgraph = "0.6"  # For learning graph structures
rayon = "1.8"     # For parallel learning computations
rand = "0.8"      # For random number generation in algorithms

# Council integration
agent-agency-council = { path = "../council" }

# Database for learning persistence
sqlx.workspace = true

