[package]
name = "agent-agency-e2e-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "agent_agency_e2e_tests"
path = "mod.rs"

[dependencies]
# Workspace dependencies
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
chrono.workspace = true

# Additional dependencies for system resource monitoring
sysinfo = "0.30"  # System information and resource monitoring
# heim = { version = "0.1.0-rc.1", features = ["cpu", "memory", "disk"] }  # Async system monitoring - causes dependency conflicts
psutil = "3.2"  # Process and system utilities
nvml-wrapper = "0.9"  # NVIDIA GPU monitoring
nvml-wrapper-sys = "0.7"  # NVIDIA management library
procfs = "0.16"  # Linux process information
systemstat = "0.2"  # System statistics
governor = "0.6"  # Rate limiting for monitoring
dashmap = "5.5"  # Concurrent hashmap for resource tracking
crossbeam = "0.8"  # Concurrent programming utilities

# Local crates
agent-agency-contracts = { path = "../agent-agency-contracts" }
