[package]
name = "agent-agency-e2e-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "agent_agency_e2e_tests"
path = "mod.rs"

[dependencies]
# Workspace dependencies
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
chrono.workspace = true

# Additional dependencies for system resource monitoring
sysinfo = "0.30"  # System information and resource monitoring
# heim = { version = "0.1.0-rc.1", features = ["cpu", "memory", "disk"] }  # Async system monitoring - disabled due to dependency conflicts
psutil = "3.2"  # Process and system utilities
nvml-wrapper = "0.9"  # NVIDIA GPU monitoring
nvml-wrapper-sys = "0.7"  # NVIDIA management library
# procfs = "0.16"  # Linux process information - not supported on macOS
systemstat = "0.2"  # System statistics
governor = "0.6"  # Rate limiting for monitoring
dashmap = "5.5"  # Concurrent hashmap for resource tracking
crossbeam = "0.8"  # Concurrent programming utilities

# Additional dependencies for test timing data parsing
serde-xml-rs = "0.6"  # XML parsing for JUnit/TestNG formats
quick-xml = "0.31"  # Fast XML parsing
regex = "1.10"  # Regular expressions for parsing
statrs = "0.16"  # Statistical analysis and distributions
streaming-stats = "0.2"  # Streaming statistical algorithms
ordered-float = "4.0"  # Ordered floating point comparisons

# Local crates
agent-agency-contracts = { path = "../agent-agency-contracts" }
orchestration = { path = "../orchestration" }
agent-agency-council = { path = "../council" }
agent-agency-workers = { path = "../workers" }
agent-agency-interfaces = { path = "../interfaces" }
agent-agency-planning-agent = { path = "../planning-agent" }
agent-agency-observability = { path = "../observability" } # Using observability for quality gates
uuid.workspace = true
rand.workspace = true

# Force compatible versions to resolve indicatif/console conflicts
indicatif = "0.17"
console = { version = "0.16", features = ["std"] }
