# Cargo configuration for optimized builds

# Fast linkers for different platforms (commented out until available)
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-Clink-arg=-fuse-ld=lld"]

# [target.aarch64-apple-darwin]
# rustflags = ["-Clink-arg=-fuse-ld=ld64.lld"]

# [target.x86_64-apple-darwin]
# rustflags = ["-Clink-arg=-fuse-ld=ld64.lld"]

# Build configuration
[build]
# Use all available cores by default (0 means auto-detect)
# jobs = 0  # Commented out as it causes issues

# Rust flags for better performance
[env]
# Enable parallel compilation
RUSTFLAGS = "-C target-cpu=native"

# Network configuration for faster dependency downloads
[net]
retry = 2
git-fetch-with-cli = true