[build]

[target.aarch64-apple-darwin]
rustflags = [
  # Dev iteration speed:
  "-C", "codegen-units=16",
  "-C", "incremental=true",
]

# Optional: speed up linker on dev (keeps symbol info)
[profile.dev]
opt-level = 1
debug = true
split-debuginfo = "packed"