[package]
name = "agent-agency-cli"
version = "0.1.0"
edition = "2021"
authors = ["Darian Rosebrook <darian@example.com>"]
description = "CLI interface for Agent Agency V3 with intervention controls"

[dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Web framework
axum = { version = "0.7", features = ["json", "ws"] }
tower-http = { version = "0.5", features = ["cors"] }
futures-util = "0.3"

# File watching
notify = "6.0"

# Lazy static initialization
lazy_static = "1.4"

# Local crates
self-prompting-agent = { path = "../self-prompting-agent" }
agent-agency-workers = { path = "../workers" }
orchestration = { path = "../orchestration" }
file_ops = { path = "../file_ops" }
agent-agency-config = { path = "../config" }
