[package]
name = "agent-agency-system-health-monitor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true

# System health monitoring specific
sysinfo = "0.30"
prometheus = "0.13"
dashmap = "5.5"
crossbeam = "0.8"
parking_lot = "0.12"
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
regex = "1.10"

# Statistical analysis
tdigest = "0.2"
hdrhistogram = "7.5"

# Redis integration
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# macOS system calls
[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
mach2 = "0.4"
core-foundation = "0.9"

# Windows system monitoring
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["pdh", "winbase", "handleapi", "processthreadsapi"] }
windows = { version = "0.52", features = ["Win32_System_Performance", "Win32_System_Wmi", "Win32_Storage_FileSystem"] }

# Database integration
sqlx = { workspace = true, features = ["postgres", "chrono", "uuid"] }

# Integration with existing V3 components (optional for basic functionality)
agent-agency-council = { path = "../council", optional = true }
agent-agency-research = { path = "../research", optional = true }
agent-agency-workers = { path = "../workers", optional = true }
agent-agency-context-preservation-engine = { path = "../context-preservation-engine", optional = true }
agent-agency-database = { path = "../database", optional = true }
agent-agency-observability = { path = "../observability", optional = true }

[features]
default = []
full = [
    "agent-agency-council",
    "agent-agency-research",
    "agent-agency-workers",
    "agent-agency-context-preservation-engine",
    "agent-agency-database",
    "agent-agency-observability"
]

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.0"
tempfile = "3.0"