[package]
name = "agent-agency-system-health-monitor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true

# System health monitoring specific
sysinfo = "0.30"
prometheus = "0.13"
dashmap = "5.5"
crossbeam = "0.8"
parking_lot = "0.12"
futures = "0.3"

# Disk I/O monitoring
procfs = "0.16"
psutil = "3.2"

# Database integration
sqlx = { workspace = true, features = ["postgres", "chrono", "uuid"] }

# Integration with existing V3 components
agent-agency-council = { path = "../council" }
agent-agency-research = { path = "../research" }
agent-agency-workers = { path = "../workers" }
agent-agency-context-preservation-engine = { path = "../context-preservation-engine" }
agent-agency-database = { path = "../database" }
agent-agency-observability = { path = "../observability" }
