[package]
name = "model-hotswap"
version = "0.1.0"
edition = "2021"
description = "Model-Agnostic Hot-Swapping - Seamless runtime model replacement with performance tracking"
license = "MIT"

[dependencies]
# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
thiserror = "1.0"

# Model management
model-benchmarking = { path = "../model-benchmarking" }
# agent-agency-apple-silicon = { path = "../apple-silicon" } # PLACEHOLDER: temp disabled to avoid libtorch

# Performance monitoring - temporarily excluded due to database dependency
# agent-agency-observability = { path = "../observability" }

# Time utilities
chrono = { version = "0.4", features = ["serde"] }

# HTTP client for model downloads
reqwest = { version = "0.11", features = ["json"] }

# LRU cache for model instances
lru = "0.12"

# Math operations for performance modeling
nalgebra = "0.32"

# Random number generation
rand = "0.8"

# Semantic versioning
semver = "1.0"

[dev-dependencies]
tokio-test = "0.4"
