[package]
name = "self-prompting-agent"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
agent-agency-contracts = { path = "../agent-agency-contracts" }
# agent-agency-council = { path = "../council" } # TEMP: still has torch deps
# reflexive-learning = { path = "../reflexive-learning" } # TEMP: depends on council
# agent-agency-workers = { path = "../workers" } # TEMP: depends on council
# agent-agency-apple-silicon = { path = "../apple-silicon" } # TEMP: has torch deps
file_ops = { path = "../file_ops" }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true, features = ["serde"] }
async-trait = { workspace = true }
reqwest = { version = "0.11", features = ["json"] }
diffy = "0.3"
git2 = "0.19"
tempfile = "3.8"
rand = "0.8"
regex = "1.10"
tokenizers = "0.15"  # HuggingFace tokenizers for proper text tokenization

# Force compatible versions to resolve indicatif/console conflicts
indicatif = "0.17"
console = { version = "0.16", features = ["std"] }

# Action request parsing
pest = "2.7"  # PEG parser for formal grammars
pest_derive = "2.7"  # Derive macros for pest
nom = "7.1"  # Parser combinators for robust parsing

# Error handling
thiserror = "1.0"  # Ergonomic error handling

# Cryptography
sha2 = "0.10"  # SHA256 hashing

# YAML serialization
serde_yaml = "0.9"  # YAML support for serde

# Async runtime utilities
futures = "0.3"  # For block_on in sync contexts

[[example]]
name = "playground_test"
path = "examples/playground_test.rs"
