[package]
name = "agent-agency-research"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

# Research-specific dependencies
reqwest = { version = "0.11", features = ["json", "stream"] }
scraper = "0.18"
url = "2.4"
chrono.workspace = true
uuid.workspace = true
dashmap = "5.5"
parking_lot = "0.12"

# Vector search and embeddings
qdrant-client = "1.10"
fxhash = "0.2"
embedding-service = { path = "../embedding-service" }

# Database integration
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls", "chrono", "uuid"] }
deadpool-postgres = "0.11"
agent-agency-database = { path = "../database" }

# Web scraping and content extraction
select = "0.6"
html5ever = "0.26"
tendril = "0.4"
encoding_rs = "0.8"

# Content processing
pulldown-cmark = "0.10"
ammonia = "3.3"
regex = "1.10"
strsim = "0.10"

[dev-dependencies]
tokio-test = "0.4"
