[package]
name = "agent-agency-production"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "agent_agency_production"
path = "mod.rs"

[dependencies]
# Workspace dependencies
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true

# Local crates
agent-agency-contracts = { path = "../agent-agency-contracts" }

# Additional dependencies
anyhow = "1.0"
statrs = "0.16"
quantiles = "0.7"
ordered-float = "4.2"
rand = "0.8"
sampling = "0.1"
jsonwebtoken = "9.2"
sha2 = "0.10"
reqwest = { version = "0.11", features = ["json"] }