[package]
name = "agent-agency-workers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
chrono.workspace = true
uuid.workspace = true
reqwest.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
config.workspace = true

# Internal crate dependencies
agent-agency-council = { path = "../council" }
agent-agency-resilience = { path = "../resilience" }
agent-agency-contracts = { path = "../agent-agency-contracts" }
agent-agency-database = { path = "../database" }
# claim-extraction = { path = "../claim-extraction" }  # Temporarily commented to resolve circular dependency

# Multimodal RAG integration dependencies
indexers = { path = "../indexers" }
agent-agency-observability = { path = "../observability" }

# Worker-specific dependencies
dashmap = "5.5"  # Concurrent hashmap for worker registry
crossbeam = "0.8"  # Lock-free data structures
parking_lot = "0.12"  # Fast mutexes for coordination
futures = "0.3"  # Async utilities
tokio-stream = "0.1"  # Stream processing
bytes = "1.5"  # Byte buffer handling

[dev-dependencies]
jsonschema = "0.17"
serde_json = "1"
tokio-test = "0.4"
tempfile = "3"
