version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: arbiter-postgres-test
    environment:
      POSTGRES_DB: arbiter_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d arbiter_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - arbiter-network

  redis:
    image: redis:7-alpine
    container_name: arbiter-redis-test
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - arbiter-network

volumes:
  postgres_data:

networks:
  arbiter-network:
    driver: bridge
