[package]
name = "agent-agency-planning-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true

# Local crates
agent-agency-contracts = { path = "../agent-agency-contracts" }
agent-agency-database = { path = "../database" }

# Additional dependencies
anyhow = "1.0"
futures = "0.3"
regex = "1.10"

# Advanced goal extraction and analysis
rust-bert = "0.21"  # BERT models for semantic understanding
tokenizers = "0.19"  # HuggingFace tokenizers
lingua = "1.6"  # Language detection
whatlang = "0.18"  # Fast language detection
comrak = "0.18"  # CommonMark markdown parser
tree-sitter = "0.20"  # Syntax tree parsing
tree-sitter-rust = "0.20"  # Rust language parsing
pest = "2.7"  # PEG parser for goal structures
pest_derive = "2.7"  # Derive macros for pest
nom = "7.1"  # Parser combinators for goal parsing
strsim = "0.10"  # String similarity algorithms
once_cell = "1.19"  # Lazy static initialization
lru = "0.12"  # LRU cache for goal analysis
priority-queue = "2.0"  # Priority queue for goal ranking
