[package]
name = "agent-agency-planning-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true

# Local crates
agent-agency-contracts = { path = "../agent-agency-contracts" }
agent-agency-caws = { path = "../caws" }
agent-agency-database = { path = "../database" }

# Additional dependencies
anyhow = "1.0"
futures = "0.3"
regex = "1.10"
