[package]
name = "simple-e2e-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "simple_e2e_tests"
path = "../simple_e2e_tests.rs"
