[package]
name = "agent-agency-api-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Core async runtime
tokio.workspace = true
clap = { version = "4.0", features = ["derive"] }

# Web framework
axum.workspace = true
tower-http.workspace = true

# Local crates
agent-agency-contracts = { path = "../agent-agency-contracts" }
# interfaces = { path = "../interfaces" } # TODO: Create interfaces crate
orchestration = { path = "../orchestration" }
