openapi: 3.0.0
info:
  title: CAWS Integration API
  version: 2.0.0
  description: |
    Local CLI handshake interface between Arbiter and CAWS tooling.
    
    Documents the command-level contracts for CAWS constitutional enforcement.
    Note: This is HTTP-agnostic (local CLI) but documented in OpenAPI style for consistency.

servers:
  - url: file://local
    description: Local CLI interface

paths:
  /caws/verify:
    post:
      summary: Verify task result against CAWS specification
      description: |
        Triggered by Arbiter before verdict.
        Runs quality gates, tests, and budget validation.
      operationId: cawsVerify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyRequest'
      responses:
        '200':
          description: Verification complete with verdict
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/Verdict'
        '400':
          description: Invalid specification or task result

  /caws/waiver/create:
    post:
      summary: Create waiver for exceptional circumstances
      description: |
        Triggered by Arbiter on budget breach or gate failure.
        Creates waiver request for human approval.
      operationId: createWaiver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaiverRequest'
      responses:
        '201':
          description: Waiver created
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/Waiver'

  /caws/audit/self:
    post:
      summary: Self-audit Arbiter code
      description: |
        Triggered by CI bootstrap or manual review.
        Validates Arbiter implementation against CAWS standards.
      operationId: auditSelf
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfAuditRequest'
      responses:
        '200':
          description: Self-audit complete
          content:
            application/yaml:
              schema:
                $ref: '#/components/schemas/SelfVerdict'

  /caws/provenance/record:
    post:
      summary: Record provenance for task execution
      description: |
        Triggered after each task completion.
        Records immutable audit trail with CAWS compliance data.
      operationId: recordProvenance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvenanceRecord'
      responses:
        '201':
          description: Provenance recorded
          content:
            application/json:
              schema:
                type: object
                properties:
                  provenanceHash:
                    type: string
                    description: Immutable hash of provenance record

components:
  schemas:
    VerifyRequest:
      type: object
      required:
        - specId
        - taskResult
      properties:
        specId:
          type: string
          description: CAWS working spec ID
        taskResult:
          type: object
          properties:
            filesChanged:
              type: integer
            linesChanged:
              type: integer
            testsPass:
              type: boolean
            lintsPass:
              type: boolean
            coveragePercent:
              type: number

    Verdict:
      type: object
      required:
        - id
        - specId
        - compliant
        - timestamp
      properties:
        id:
          type: string
          description: Unique verdict ID
        specId:
          type: string
        compliant:
          type: boolean
        budgetStatus:
          type: object
          properties:
            filesBudget:
              type: object
              properties:
                used:
                  type: integer
                limit:
                  type: integer
                compliant:
                  type: boolean
            locBudget:
              type: object
              properties:
                used:
                  type: integer
                limit:
                  type: integer
                compliant:
                  type: boolean
        qualityGates:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              passed:
                type: boolean
              mandatory:
                type: boolean
        violations:
          type: array
          items:
            type: string
        waiverRequired:
          type: boolean
        timestamp:
          type: string
          format: date-time
        provenanceHash:
          type: string

    WaiverRequest:
      type: object
      required:
        - title
        - reason
        - description
        - gates
        - expiresAt
      properties:
        title:
          type: string
        reason:
          type: string
          enum:
            - emergency_hotfix
            - legacy_integration
            - experimental_feature
            - third_party_constraint
            - performance_critical
            - security_patch
            - infrastructure_limitation
            - other
        description:
          type: string
        gates:
          type: array
          items:
            type: string
        expiresAt:
          type: string
          format: date-time
        approvedBy:
          type: string
        impactLevel:
          type: string
          enum: [low, medium, high, critical]
        mitigationPlan:
          type: string

    Waiver:
      type: object
      properties:
        id:
          type: string
          pattern: ^WV-[A-Z0-9]+-\d+$
        title:
          type: string
        status:
          type: string
          enum: [pending, approved, rejected, expired, revoked]
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

    SelfAuditRequest:
      type: object
      required:
        - targetPath
        - cawsStandards
      properties:
        targetPath:
          type: string
          description: Path to Arbiter code to audit
        cawsStandards:
          type: array
          items:
            type: string
          description: CAWS standards to validate against

    SelfVerdict:
      type: object
      properties:
        id:
          type: string
          pattern: ^SELF-VERDICT-\d+$
        compliant:
          type: boolean
        findings:
          type: array
          items:
            type: object
            properties:
              standard:
                type: string
              status:
                type: string
                enum: [pass, fail, waiver]
              details:
                type: string
        timestamp:
          type: string
          format: date-time

    ProvenanceRecord:
      type: object
      required:
        - taskId
        - agentId
        - verdictId
        - timestamp
      properties:
        taskId:
          type: string
        agentId:
          type: string
        verdictId:
          type: string
        cawsCompliant:
          type: boolean
        waiverIds:
          type: array
          items:
            type: string
        gatesPassed:
          type: array
          items:
            type: string
        budgetAdherence:
          type: object
          properties:
            filesUsed:
              type: integer
            filesLimit:
              type: integer
            locUsed:
              type: integer
            locLimit:
              type: integer
        qualityScores:
          type: object
          additionalProperties:
            type: number
        timestamp:
          type: string
          format: date-time
        arbiterSignature:
          type: string
          description: Cryptographic signature of arbiter verdict

