[package]
name = "agent-agency-security-policy-enforcer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true

# Security-specific dependencies
regex = "1.10"
glob = "0.3"
pathdiff = "0.2"
walkdir = "2.4"
ignore = "0.4"
git2 = "0.19"

# File system and process security
libc = "0.2"
nix = "0.28"

# Compression for log archiving
flate2 = "1.0"

# Cryptographic dependencies
ring = "0.17"
base64 = "0.22"
hex = "0.4"

# Council integration for security decisions
agent-agency-agent-agency-council = { path = "../council" }

# Provenance integration for audit trails
agent-agency-provenance = { path = "../provenance" }
