# Clippy configuration for agent-agency project
# @darianrosebrook

# Specific configuration
cognitive-complexity-threshold = 30
too-many-lines-threshold = 100
disallowed-names = ["foo", "bar", "baz", "tmp"]

# Clippy version compatibility
msrv = "1.70"
