# Rustfmt configuration for agent-agency project
# @darianrosebrook

# Basic formatting
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Function formatting
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Struct and enum formatting
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

# Comments and documentation
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = true
format_strings = true

# Spacing
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"

# Trailing
trailing_comma = "Vertical"
trailing_semicolon = true

# Misc
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
