# Rustfmt configuration for agent-agency project
# @darianrosebrook

# Basic formatting (stable features only)
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Import formatting (stable features only)
reorder_imports = true
reorder_modules = true

# Function formatting (stable features only)
fn_params_layout = "Tall"

# Comments and documentation (stable features only)
normalize_comments = true
normalize_doc_attributes = true

# Spacing (stable features only)
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true

# Trailing (stable features only)
trailing_comma = "Vertical"