[package]
name = "agent-agency-worker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Core async runtime
tokio.workspace = true
clap = { version = "4.0", features = ["derive"] }

# Web framework
axum.workspace = true
tower-http.workspace = true

# JSON handling
serde.workspace = true
serde_json.workspace = true

# UUID handling
uuid.workspace = true

# Date/time
chrono.workspace = true

