[package]
name = "agent-agency-apple-silicon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

# Apple Silicon specific dependencies
core-foundation = "0.9"
objc = "0.2"
metal = "0.29"
dispatch = "0.2"
once_cell = "1.19"
# metal-performance-shaders = "0.1"  # This crate doesn't exist, will use Metal directly

# Core ML integration
objc2-core-ml = "0.3"
objc2-foundation = "0.3"

# ML/AI integration
candle-core = "0.9.1"
candle-nn = "0.9.1"
candle-transformers = "0.9.1"

# System monitoring
sysinfo = "0.30"

# Directory utilities
dirs = "5.0"

[dev-dependencies]
tokio-test = "0.4"
