[package]
name = "agent-agency-apple-silicon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
tokio-util = "0.7"
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

# Apple Silicon specific dependencies (gated by target)
core-foundation = "0.9"
objc = "0.2"
once_cell = "~1.19"
num_cpus = "1.16"

# Only activate Metal/Apple Silicon crates on arm64 macOS
[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
metal = "0.29"
dispatch = "0.2"
objc2 = "0.5"
objc2-core-ml = "0.3"
objc2-foundation = "0.3"
objc2-metal-performance-shaders = "0.3"
objc2-metal-performance-shaders-graph = "0.3"

# IOKit integration for hardware monitoring
# Note: IOKit bindings not available in crates.io, would need custom bindings

# ML/AI integration
candle-core = { version = "0.9.1", optional = true }
candle-nn = { version = "0.9.1", optional = true }
candle-transformers = { version = "0.9.1", optional = true }
safetensors = "0.4"
ort = { version = "2.0.0-rc.10", optional = true }
protobuf = "3.4"

# Quantization and optimization
# candle-flash-attn = "0.9.1"  # Flash attention for efficiency - requires CUDA which isn't available
tch = { workspace = true, optional = true }  # PyTorch bindings for quantization
# candle-flash-attn-v3 = "0.9.1"  # Advanced attention mechanisms

# System monitoring
sysinfo = "0.30"

# Additional ML/ML dependencies
lru = "0.12"

# Text processing
regex = "1.10"
tokenizers = "0.19"

# Image processing
image = { version = "0.24", features = ["jpeg", "png", "webp", "tiff", "bmp", "gif"] }
imageproc = "0.23"
# exif = "0.0.1"  # EXIF metadata extraction - uses deprecated features
imgref = "1.10"  # Image reference types
rgb = "0.8"  # RGB color types

# Concurrent data structures
dashmap = "5.5"
parking_lot = "0.12"

# Additional ML/ML dependencies
bytemuck = "1.14"
half = "2.4"
ndarray = "0.15"

# Observability and caching - temporarily disabled due to compilation issues
# agent-agency-observability = { path = "../observability" }

# Metrics and monitoring
prometheus = "0.13"
warp = "0.3"
cadence = "0.29"

# Half-precision floating point support already included above

# Compression algorithms
flate2 = "1.0"  # Gzip/zlib compression
zstd = "0.13"   # Zstandard compression
brotli = "6.0"  # Brotli compression

# Byte manipulation utilities

# Directory utilities
dirs = "5.0"
sha2 = "0.10"
hex = "0.4"
libc = "0.2"
strsim = "0.11"  # String similarity for embedding lookups

[dev-dependencies]
tokio-test = "0.4"

[features]
default = ["cpu"]                    # sensible dev default on Intel
cpu = []
coreml = []                          # Core ML support (available on both Intel and Apple Silicon)
torch = ["tch"]                      # PyTorch bindings for quantization
mpsgraph = []                        # Metal Performance Shaders Graph (Apple Silicon only)
candle = ["candle-core", "candle-nn", "candle-transformers"] # Candle ML framework support
ort = ["dep:ort"]                    # ONNX Runtime support
