apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesStrategicMerge:
  - ingress-aws.yml
  - storage-aws.yml
  - monitoring-aws.yml

images:
  - name: agent-agency/orchestrator
    newTag: v3.0.0-aws
  - name: agent-agency/council
    newTag: v3.0.0-aws

configMapGenerator:
  - name: agent-agency-config
    behavior: merge
    literals:
      - AWS_REGION=us-east-1
      - STORAGE_CLASS=gp3
      - MONITORING_ENABLED=true

secretGenerator:
  - name: agent-agency-secrets
    behavior: merge
    literals:
      - aws-region=us-east-1
      - database-password=CHANGE_ME_IN_PRODUCTION
