[package]
name = "runtime-optimization"
version = "0.1.0"
edition = "2021"
description = "Kokoro-inspired hyper-tuning pipeline for Agent Agency V3 runtime optimization"
license = "MIT"

[dependencies]
# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
thiserror = "1.0"

# Apple Silicon integration
agent-agency-apple-silicon = { path = "../apple-silicon" }

# Council and CAWS integration
council = { path = "../council" }
# caws-runtime-validator = { path = "../caws/runtime-validator" } # TODO: Implement runtime validator

# Performance monitoring
observability = { path = "../observability" }

# Model benchmarking for performance feedback
model-benchmarking = { path = "../model-benchmarking" }

# Statistical analysis for Bayesian optimization
statrs = "0.16"
rand = "0.8"

# Time utilities
chrono = { version = "0.4", features = ["serde"] }

# Math operations
nalgebra = "0.32"

# LRU cache for decision caching
lru = "0.12"

[dev-dependencies]
tokio-test = "0.4"
