#!/bin/bash
# Fix all mangled imports from over-replacement

echo "Fixing mangled imports..."

# Fix all the mangled import patterns
for file in $(find iterations/v3 -name "*.rs" -type f); do
    # Fix types imports
    sed -i '' 's/extraction_prompting_extraction_types/extraction_types/g' "$file"
    sed -i '' 's/prompting_prompting_indexer_types/indexer_types/g' "$file"
    sed -i '' 's/data_processing_prompting_data_processing_types/data_processing_types/g' "$file"
    sed -i '' 's/mcp_prompting_mcp_types/mcp_types/g' "$file"
    sed -i '' 's/memory_prompting_memory_types/memory_types/g' "$file"
    sed -i '' 's/worker_prompting_worker_types/worker_types/g' "$file"
    sed -i '' 's/cache_prompting_cache_types/cache_types/g' "$file"
    sed -i '' 's/engine_prompting_engine_types/engine_types/g' "$file"
    sed -i '' 's/council_prompting_council_types/council_types/g' "$file"
    sed -i '' 's/embedding_prompting_embedding_types/embedding_types/g' "$file"
    sed -i '' 's/enricher_prompting_enricher_types/enricher_types/g' "$file"
    sed -i '' 's/indexer_prompting_indexer_types/indexer_types/g' "$file"
    sed -i '' 's/ingestor_prompting_ingestor_types/ingestor_types/g' "$file"
    sed -i '' 's/knowledge_prompting_knowledge_types/knowledge_types/g' "$file"
    sed -i '' 's/evaluator_prompting_evaluator_types/evaluator_types/g' "$file"
    sed -i '' 's/benchmark_prompting_benchmark_types/benchmark_types/g' "$file"
    sed -i '' 's/parallel_prompting_parallel_types/parallel_types/g' "$file"
    sed -i '' 's/provenance_prompting_provenance_types/provenance_types/g' "$file"
    sed -i '' 's/recovery_prompting_recovery_types/recovery_types/g' "$file"
    sed -i '' 's/reflexive_prompting_reflexive_types/reflexive_types/g' "$file"
    sed -i '' 's/research_prompting_research_types/research_types/g' "$file"
    sed -i '' 's/policy_prompting_policy_types/policy_types/g' "$file"
    sed -i '' 's/integrity_prompting_integrity_types/integrity_types/g' "$file"
    sed -i '' 's/health_prompting_health_types/health_types/g' "$file"
    sed -i '' 's/state_prompting_state_types/state_types/g' "$file"
    sed -i '' 's/observability_prompting_observability_types/observability_types/g' "$file"
    sed -i '' 's/common_errors_prompting_common_errors/common_errors/g' "$file"
    sed -i '' 's/api_errors_prompting_api_errors/api_errors/g' "$file"
    sed -i '' 's/worker_errors_prompting_worker_errors/worker_errors/g' "$file"
    sed -i '' 's/planning_errors_prompting_planning_errors/planning_errors/g' "$file"
    sed -i '' 's/council_errors_prompting_council_errors/council_errors/g' "$file"
    sed -i '' 's/contract_errors_prompting_contract_errors/contract_errors/g' "$file"
    sed -i '' 's/observability_errors_prompting_observability_errors/observability_errors/g' "$file"
    sed -i '' 's/common_metrics_prompting_common_metrics/common_metrics/g' "$file"
    sed -i '' 's/memory_metrics_prompting_memory_metrics/memory_metrics/g' "$file"
    sed -i '' 's/coordinator_metrics_prompting_coordinator_metrics/coordinator_metrics/g' "$file"
    sed -i '' 's/consensus_metrics_prompting_consensus_metrics/consensus_metrics/g' "$file"
    sed -i '' 's/orchestrator_metrics_prompting_orchestrator_metrics/orchestrator_metrics/g' "$file"
    sed -i '' 's/database_metrics_prompting_database_metrics/database_metrics/g' "$file"
    sed -i '' 's/dashboard_metrics_prompting_dashboard_metrics/dashboard_metrics/g' "$file"
    sed -i '' 's/analytics_metrics_prompting_analytics_metrics/analytics_metrics/g' "$file"
    sed -i '' 's/observability_metrics_prompting_observability_metrics/observability_metrics/g' "$file"
    sed -i '' 's/recovery_metrics_prompting_recovery_metrics/recovery_metrics/g' "$file"
    sed -i '' 's/knowledge_metrics_prompting_knowledge_metrics/knowledge_metrics/g' "$file"
    sed -i '' 's/vector_metrics_prompting_vector_metrics/vector_metrics/g' "$file"
    sed -i '' 's/health_metrics_prompting_health_metrics/health_metrics/g' "$file"
    sed -i '' 's/prompting_parallel_types/parallel_types/g' "$file"
    sed -i '' 's/prompting_prompting_parallel_types/parallel_types/g' "$file"
done

echo "Mangled imports fixed!"
