[package]
name = "knowledge-ingestor"
version = "0.1.0"
edition = "2021"
authors = ["@darianrosebrook"]

[dependencies]
# Core dependencies
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
agent-agency-database = { path = "../database" }
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Embedding service
embedding-service = { path = "../embedding-service", optional = true }

# Compression and parsing
flate2 = "1.0"
tar = "0.4"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# String processing
unicode-normalization = "0.1"
regex = "1.10"

# Caching
lru = "0.12"

# Rate limiting
governor = "0.6"
nonzero_ext = "0.3"

# CLI (for bin targets)
clap = { version = "4.4", features = ["derive"] }

[features]
default = []
embeddings = ["embedding-service"]

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"

[[bin]]
name = "load_core_vocabulary"
path = "src/bin/load_core_vocabulary.rs"

