[package]
name = "federated-learning"
version = "0.1.0"
edition = "2021"
description = "Federated Privacy-Preserving Learning - Cross-tenant model improvement without data sharing"
license = "MIT"

[dependencies]
# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
thiserror = "1.0"

# Cryptography for secure aggregation
ring = "0.17"
rust-crypto = "0.2"

# Model handling
model-benchmarking = { path = "../model-benchmarking" }

# Observability
observability = { path = "../observability" }

# Time utilities
chrono = { version = "0.4", features = ["serde"] }

# Math operations for aggregation
nalgebra = "0.32"

# Secure communication
tokio-tungstenite = "0.20"
futures-util = "0.3"

# Random number generation for differential privacy
rand = "0.8"

[dev-dependencies]
tokio-test = "0.4"
