//! Semantic Clustering
//!
//! Groups memories by semantic similarity using vector embeddings.

use crate::consolidation::*;
use std::collections::HashMap;

/// K-means clustering for semantic memory grouping
pub struct SemanticClustering {
    max_iterations: usize,
    convergence_threshold: f32,
}

impl SemanticClustering {
    pub fn new(max_iterations: usize, convergence_threshold: f32) -> Self {
        Self {
            max_iterations,
            convergence_threshold,
        }
    }

    /// Perform k-means clustering on memory embeddings
    pub async fn cluster_memories(
        &self,
        memory_embeddings: Vec<(crate::memory_types::MemoryId, Vec<f32>)>,
        k: usize,
    ) -> crate::MemoryResult<Vec<MemoryCluster>> {
        if memory_embeddings.is_empty() {
            return Ok(Vec::new());
        }

        if k == 0 || k > memory_embeddings.len() {
            return Ok(Vec::new());
        }

        let mut centroids = self.initialize_centroids(&memory_embeddings, k);
        let mut clusters: Vec<MemoryCluster> = Vec::new();

        let mut assignments = Vec::new();

        for iteration in 0..self.max_iterations {
            // Assign memories to nearest centroids
            assignments = self.assign_to_centroids(&memory_embeddings, &centroids);

            // Update centroids
            let new_centroids = self.update_centroids(&memory_embeddings, &assignments, k);

            // Check for convergence
            if self.has_converged(&centroids, &new_centroids) {
                break;
            }

            centroids = new_centroids;
        }

        // Create final clusters
        for i in 0..k {
            let member_memories: Vec<crate::memory_types::MemoryId> = memory_embeddings
                .iter()
                .enumerate()
                .filter_map(|(idx, (memory_id, _))| {
                    if assignments[idx] == i {
                        Some(memory_id.clone())
                    } else {
                        None
                    }
                })
                .collect();

            if !member_memories.is_empty() {
                let cluster = MemoryCluster {
                    cluster_id: format!("cluster_{}_{}", i, chrono::Utc::now().timestamp_millis()),
                    centroid_embedding: centroids[i].clone(),
                    member_memories,
                    cluster_summary: None, // Will be generated by summarization
                    importance_score: self.calculate_cluster_importance(
                        &memory_embeddings,
                        &assignments,
                        i,
                    ),
                    created_at: chrono::Utc::now(),
                    last_updated: chrono::Utc::now(),
                };
                clusters.push(cluster);
            }
        }

        Ok(clusters)
    }

    /// Initialize centroids using k-means++ algorithm
    fn initialize_centroids(
        &self,
        memory_embeddings: &[(crate::memory_types::MemoryId, Vec<f32>)],
        k: usize,
    ) -> Vec<Vec<f32>> {
        let mut centroids = Vec::new();
        let mut rng = rand::thread_rng();

        // Choose first centroid randomly
        let first_idx = rand::Rng::gen_range(&mut rng, 0..memory_embeddings.len());
        centroids.push(memory_embeddings[first_idx].1.clone());

        for _ in 1..k {
            let mut distances = vec![0.0; memory_embeddings.len()];

            // Calculate distance to nearest existing centroid for each point
            for (i, (_, embedding)) in memory_embeddings.iter().enumerate() {
                let mut min_distance = f32::INFINITY;
                for centroid in &centroids {
                    let distance = self.euclidean_distance(embedding, centroid);
                    min_distance = min_distance.min(distance);
                }
                distances[i] = min_distance;
            }

            // Choose next centroid with probability proportional to squared distance
            let total_distance: f32 = distances.iter().sum();
            let mut cumulative_prob = 0.0;
            let rand_val = rand::Rng::gen::<f32>(&mut rng);

            for (i, &distance) in distances.iter().enumerate() {
                cumulative_prob += distance / total_distance;
                if rand_val <= cumulative_prob {
                    centroids.push(memory_embeddings[i].1.clone());
                    break;
                }
            }
        }

        centroids
    }

    /// Assign each memory to the nearest centroid
    fn assign_to_centroids(
        &self,
        memory_embeddings: &[(crate::memory_types::MemoryId, Vec<f32>)],
        centroids: &[Vec<f32>],
    ) -> Vec<usize> {
        memory_embeddings
            .iter()
            .map(|(_, embedding)| {
                let mut best_centroid = 0;
                let mut best_distance = f32::INFINITY;

                for (i, centroid) in centroids.iter().enumerate() {
                    let distance = self.euclidean_distance(embedding, centroid);
                    if distance < best_distance {
                        best_distance = distance;
                        best_centroid = i;
                    }
                }

                best_centroid
            })
            .collect()
    }

    /// Update centroids as mean of assigned points
    fn update_centroids(
        &self,
        memory_embeddings: &[(crate::memory_types::MemoryId, Vec<f32>)],
        assignments: &[usize],
        k: usize,
    ) -> Vec<Vec<f32>> {
        let mut new_centroids = vec![vec![0.0; memory_embeddings[0].1.len()]; k];
        let mut counts = vec![0; k];

        // Sum embeddings for each cluster
        for (i, (_, embedding)) in memory_embeddings.iter().enumerate() {
            let cluster_idx = assignments[i];
            for (j, &val) in embedding.iter().enumerate() {
                new_centroids[cluster_idx][j] += val;
            }
            counts[cluster_idx] += 1;
        }

        // Calculate mean for each cluster
        for i in 0..k {
            if counts[i] > 0 {
                for val in &mut new_centroids[i] {
                    *val /= counts[i] as f32;
                }
            } else {
                // If cluster is empty, keep old centroid (handled by initialization)
            }
        }

        new_centroids
    }

    /// Check if centroids have converged
    fn has_converged(&self, old_centroids: &[Vec<f32>], new_centroids: &[Vec<f32>]) -> bool {
        old_centroids
            .iter()
            .zip(new_centroids.iter())
            .all(|(old, new)| self.euclidean_distance(old, new) < self.convergence_threshold)
    }

    /// Calculate importance score for a cluster
    fn calculate_cluster_importance(
        &self,
        memory_embeddings: &[(crate::memory_types::MemoryId, Vec<f32>)],
        assignments: &[usize],
        cluster_idx: usize,
    ) -> f32 {
        let cluster_memories: Vec<_> = memory_embeddings
            .iter()
            .enumerate()
            .filter_map(|(i, (memory_id, embedding))| {
                if assignments[i] == cluster_idx {
                    Some((memory_id, embedding))
                } else {
                    None
                }
            })
            .collect();

        if cluster_memories.is_empty() {
            return 0.0;
        }

        // TODO: Calculate actual importance scores for cluster memories
        //       Currently uses cluster size as proxy; should calculate actual importance scores based on memory relevance and recency.
        //
        // COMPLETION CHECKLIST:
        // [ ] Primary functionality implemented
        // [ ] API/data structures defined & stable
        // [ ] Error handling + validation aligned with error taxonomy
        // [ ] Tests: Unit ≥80% branch coverage (≥50% mutation if enabled)
        // [ ] Integration tests for external systems/contracts
        // [ ] Documentation: public API + system behavior
        // [ ] Performance/profiled against SLA (CPU/mem/latency throughput)
        // [ ] Security posture reviewed (inputs, authz, sandboxing)
        // [ ] Observability: logs (debug), metrics (SLO-aligned), tracing
        // [ ] Configurability and feature flags defined if relevant
        // [ ] Failure-mode cards documented (degradation paths)
        //
        // ACCEPTANCE CRITERIA:
        // - Importance scores are calculated accurately
        // - Relevance and recency are considered
        // - Scores reflect actual memory importance
        // - Calculation handles edge cases
        //
        // DEPENDENCIES:
        // - Importance scoring algorithms (Required)
        // - Relevance calculation utilities (Required)
        // - Recency tracking infrastructure (Required)
        //
        // ESTIMATED EFFORT: 4-5 hours (medium confidence)
        // PRIORITY: Medium
        // BLOCKING: No
        //
        // GOVERNANCE:
        // - CAWS Tier: 2 (memory analysis feature)
        // - Change Budget: ~100 LOC
        // - Reviewer Requirements: Memory analysis expertise
        cluster_memories.len() as f32 / memory_embeddings.len() as f32 // Temporary: cluster size proxy until actual importance scores
    }

    /// Calculate Euclidean distance between two vectors
    fn euclidean_distance(&self, a: &[f32], b: &[f32]) -> f32 {
        a.iter()
            .zip(b.iter())
            .map(|(x, y)| (x - y).powi(2))
            .sum::<f32>()
            .sqrt()
    }
}

/// Hierarchical clustering for memory organization
pub struct HierarchicalClustering {
    linkage_method: LinkageMethod,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LinkageMethod {
    Single,   // Minimum distance
    Complete, // Maximum distance
    Average,  // Average distance
    Ward,     // Ward's minimum variance
}

impl HierarchicalClustering {
    pub fn new(linkage_method: LinkageMethod) -> Self {
        Self { linkage_method }
    }

    /// Build hierarchical clusters
    pub async fn build_hierarchy(
        &self,
        memory_embeddings: Vec<(crate::memory_types::MemoryId, Vec<f32>)>,
    ) -> crate::MemoryResult<Vec<MemoryCluster>> {
        if memory_embeddings.is_empty() {
            return Ok(Vec::new());
        }

        // Calculate distance matrix
        let distance_matrix = self.calculate_distance_matrix(&memory_embeddings);

        // Perform hierarchical clustering
        let clusters = self.agglomerative_clustering(memory_embeddings, distance_matrix);

        Ok(clusters)
    }

    /// Calculate pairwise distance matrix
    fn calculate_distance_matrix(
        &self,
        memory_embeddings: &[(crate::memory_types::MemoryId, Vec<f32>)],
    ) -> Vec<Vec<f32>> {
        let n = memory_embeddings.len();
        let mut matrix = vec![vec![0.0; n]; n];

        for i in 0..n {
            for j in (i + 1)..n {
                let distance =
                    self.euclidean_distance(&memory_embeddings[i].1, &memory_embeddings[j].1);
                matrix[i][j] = distance;
                matrix[j][i] = distance;
            }
        }

        matrix
    }

    /// Agglomerative clustering implementation
    fn agglomerative_clustering(
        &self,
        mut memory_embeddings: Vec<(crate::memory_types::MemoryId, Vec<f32>)>,
        mut distance_matrix: Vec<Vec<f32>>,
    ) -> Vec<MemoryCluster> {
        let mut clusters = Vec::new();

        // Start with each memory as its own cluster
        for (memory_id, embedding) in &memory_embeddings {
            clusters.push(MemoryCluster {
                cluster_id: format!("leaf_{}", memory_id.simple()),
                centroid_embedding: embedding.clone(),
                member_memories: vec![memory_id.clone()],
                cluster_summary: None,
                importance_score: 1.0, // Individual memories have high importance
                created_at: chrono::Utc::now(),
                last_updated: chrono::Utc::now(),
            });
        }

        // Implemented: Comprehensive cluster merging with distance threshold
        // Merges clusters based on distance threshold until target count reached or no more merges possible

        // Default distance threshold: 0.5 (can be made configurable)
        // This represents a reasonable semantic similarity threshold for embeddings
        let distance_threshold = 0.5;

        // Target: reduce to approximately 10% of original clusters, but at least 1
        let target_cluster_count = (clusters.len() as f32 * 0.1).max(1.0) as usize;

        // Continue merging until target count reached or no more merges possible
        while clusters.len() > target_cluster_count {
            // Find the closest pair of clusters
            let mut best_pair: Option<(usize, usize, f32)> = None;
            let mut min_distance = f32::INFINITY;

            for i in 0..clusters.len() {
                for j in (i + 1)..clusters.len() {
                    let distance = self.calculate_cluster_distance(&clusters[i], &clusters[j]);

                    if distance < min_distance && distance <= distance_threshold {
                        min_distance = distance;
                        best_pair = Some((i, j, distance));
                    }
                }
            }

            // If no pair found within threshold, stop merging
            if let Some((idx1, idx2, _)) = best_pair {
                // Merge clusters: idx2 into idx1 (always merge into smaller index to maintain order)
                let cluster2 = clusters.remove(idx2);
                let cluster1 = &mut clusters[idx1];

                // Merge member memories
                cluster1.member_memories.extend(cluster2.member_memories);

                // Recalculate centroid as weighted average of embeddings
                cluster1.centroid_embedding =
                    self.calculate_centroid(&cluster1.member_memories, &memory_embeddings);

                // Update cluster metadata
                cluster1.cluster_id = format!("merged_{}", chrono::Utc::now().timestamp_millis());
                cluster1.last_updated = chrono::Utc::now();

                // Recalculate importance score (average of merged clusters)
                cluster1.importance_score =
                    (cluster1.importance_score + cluster2.importance_score) / 2.0;
            } else {
                // No more merges possible within threshold
                break;
            }
        }

        clusters
    }

    /// Calculate distance between two clusters based on linkage method
    fn calculate_cluster_distance(
        &self,
        cluster1: &MemoryCluster,
        cluster2: &MemoryCluster,
    ) -> f32 {
        match self.linkage_method {
            LinkageMethod::Single => {
                // Single linkage: minimum distance between any two points in clusters
                // For efficiency, use centroid distance as approximation
                self.euclidean_distance(&cluster1.centroid_embedding, &cluster2.centroid_embedding)
            }
            LinkageMethod::Complete => {
                // Complete linkage: maximum distance between any two points in clusters
                // For efficiency, use centroid distance as approximation
                self.euclidean_distance(&cluster1.centroid_embedding, &cluster2.centroid_embedding)
            }
            LinkageMethod::Average => {
                // Average linkage: average distance between all pairs
                // Use centroid distance as approximation
                self.euclidean_distance(&cluster1.centroid_embedding, &cluster2.centroid_embedding)
            }
            LinkageMethod::Ward => {
                // Ward's method: minimizes increase in within-cluster variance
                // Use centroid distance weighted by cluster sizes
                let base_distance = self
                    .euclidean_distance(&cluster1.centroid_embedding, &cluster2.centroid_embedding);
                let size1 = cluster1.member_memories.len() as f32;
                let size2 = cluster2.member_memories.len() as f32;
                base_distance * (size1 * size2 / (size1 + size2)).sqrt()
            }
        }
    }

    /// Calculate centroid embedding for a cluster from its member memories
    fn calculate_centroid(
        &self,
        member_memories: &[crate::memory_types::MemoryId],
        memory_embeddings: &[(crate::memory_types::MemoryId, Vec<f32>)],
    ) -> Vec<f32> {
        if member_memories.is_empty() {
            return Vec::new();
        }

        // Create a lookup map for quick access
        let embedding_map: std::collections::HashMap<_, _> = memory_embeddings
            .iter()
            .map(|(id, emb)| (id, emb))
            .collect();

        // Find embeddings for member memories
        let embeddings: Vec<&Vec<f32>> = member_memories
            .iter()
            .filter_map(|id| embedding_map.get(id).copied())
            .collect();

        if embeddings.is_empty() {
            return Vec::new();
        }

        let dimension = embeddings[0].len();
        let mut centroid = vec![0.0; dimension];

        // Calculate average of all embeddings
        for embedding in &embeddings {
            for (i, &value) in embedding.iter().enumerate() {
                if i < dimension {
                    centroid[i] += value;
                }
            }
        }

        let count = embeddings.len() as f32;
        for value in &mut centroid {
            *value /= count;
        }

        centroid
    }

    /// Calculate Euclidean distance between two vectors
    fn euclidean_distance(&self, a: &[f32], b: &[f32]) -> f32 {
        if a.len() != b.len() {
            return f32::INFINITY;
        }
        a.iter()
            .zip(b.iter())
            .map(|(x, y)| (x - y).powi(2))
            .sum::<f32>()
            .sqrt()
    }
}
