[package]
name = "agent-agency-council"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "macros"] }
chrono.workspace = true
uuid.workspace = true
reqwest.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
config.workspace = true

# Council-specific dependencies
dashmap = "5.5"  # Concurrent hashmap for verdict storage
crossbeam = "0.8"  # Lock-free data structures
parking_lot = "0.12"  # Fast mutexes for coordination
regex = "1.10"  # Regex patterns for claim extraction
rand = "0.8"  # Random jitter for retry logic

# Cryptographic dependencies
ring = "0.17"  # Cryptographic primitives
sha2 = "0.10"  # SHA-2 hashing
hex = "0.4"  # Hex encoding/decoding
base64 = "0.21"  # Base64 encoding/decoding

# Embedding service integration
embedding-service = { path = "../embedding-service" }

# Claim extraction integration
claim-extraction = { path = "../claim-extraction" }

# Database integration
agent-agency-database = { path = "../database" }

[dev-dependencies]
jsonschema = "0.17"
serde_json = "1"
tokio-test = "0.4"
